# project = TF_VAR_projectid
region = "us-east1"
zone = "us-east1-b"
wkstation_boot_disk_size_gb = 100
wkstation_machine_type = "e2-standard-2"
service_account_email = ""
os_image = "ubuntu-pro-2004-lts"
desired_status = "RUNNING"
machine_name = "Work Station for Development"